Tasks Service Documentation (CRUD) 
==================================
:Author: Mike Amundsen
:Email:  mike@mamund.com

== Overview
This service provides a simple tasks management interface for creating and
marking tasks complete. There is also an option to filter tasks by title.

=== RFC2119 Words
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", 
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be 
interpreted as described in link:http://tools.ietf.org/html/rfc2119[RFC2119].

=== Media Type support
All server response bodies SHOULD be returned using the 
link:http://tools.ietf.org/search/rfc4627[JSON Media Type]. All client request
bodies MUST be returned using the +application/x-www-form-urlencoded+ 
link:http://tools.ietf.org/search/rfc1866#section-8.2.1[Form Media Type]

== URLs and Operations
Below is the list of URLs and the operations they perform.

[[task-url]]
=== /tasks/
The +/tasks/+ URL supports the following HTTP methods:

 . +GET+ using the xref:query-filter[Query Filter] returns the 
xref:list-response[List Response]
 . +GET+ without arguments returns the xref:list-response[List Response]
 . +POST+ using the xref:create-payload[Create Payload] returns the 
xref:no-content-response[No Content Response]

[[complete-url]]
=== /tasks/complete
The +/tasks/complete+ URL supports the following HTTP methods:

. +POST+ using the xref:complete-payload[Complete Payload] returns the 
xref:no-content-response[No Content Response]

== Payloads
Below is a list of payloads and query strings that can be sent from the client 
to the server along with a list of the common server responses.

[[create-payload]]
=== Create Payload
Send this payload when you want to create a new task in the list:

.Create Payload
----
title=this%20is%20a%20new%20task
----

Note this payload is a simple name/value pair in ASCII text. You MUST use +POST+
to send this payload to the xref:task-url[Task URL]. You SHOULD used the following
header:

+Content-Type=application/x-www-form-urlencoded+

Upon successful completion of the operation, the server SHOULD return the 
xref:no-content-response[No Content Response]. If the operation is not succesful, 
the server MUST return the appropriate HTTP status code and the 
xref:error-response[Error Response].

[[complete-payload]]
=== Complete Payload
Send this payload when you want to mark a task as completed:

.Complete Payload
----
id={id}
----

Where +{id}+ is the ID value of the task you wish to mark completed.

Note this payload is a simple name/value pair in ASCII text. You MUST use +POST+
to send this payload to the xref:complete-url[Complete URL]. You SHOULD used the 
following header when making the HTTP request:

+Content-Type=application/x-www-form-urlencoded+

Upon successful completion of the operation, the server SHOULD return the 
xref:no-content-response[No Content Response]. If the operation is not succesful, 
the server MUST return the appropriate HTTP status code and the 
xref:error-response[Error Response].

[[query-filter]]
=== Query Filter
Send this query string when you want to filter the list of tasks by title:

.Query Filter
----
?title={title-fragment}
----

Where +{title-fragment}+ is some portion of the title string you wish to search
for in the list. For example +?title=work+ will return all the tasks with the 
word +work+ in the title.

Note this is a query string and not a payload. The client MUST append this string 
to the xref:task-url[Task URL]. The client MUST use the +HTTP GET+ method when 
executing this request.

Upon successful completion of the operation, the server SHOULD return the 
xref:list-response[List Response]. If the operation is not succesful, 
the server MUST return the appropriate HTTP status code and the 
xref:error-response[Error Response].

== Responses
Below is a list of the common responses from the server.

[[list-response]]
=== List Response
The HTTP status code 200 is returned with the following body:

.List Response
----
{
  tasks: 
  [
    {id:"1", title:"task one"},
    {id:"2", title:"task two"},
    ...
    {id:"99", title: "tasks ninetynine"}
  ]
}
----

The server SHOULD return this response when the xref:query-filter[Query] or 
GET +/tasks/+ operation is successful.

[[no-content-response]]
=== No Content Response
The HTTP status code 204 is returned with no body.

The server SHOULD return this response when the xref:create-payload[Create] or 
xref:complete-payload[Complete] operation is successful.

[[error-response]]
=== Error Response
The HTTP status code returned is in the 4xx or 5xx family and an appropriate
error message is included in the body. For example:

.Error Response
----
404 No Found HTTP/1.1
Content-Type: application/json
Length: xxx

{error:"badId", message:"Invalid task Id. Please try again"}
----

The server MUST return this response when any requested operations fails.

== Extensibility
This document describes the Tasks CRUD service. Any extensions to this service
MUST not redefine or change the use/meaning of any URLs, objects (or their properties), 
arrays, properties, etc. defined in this document. Clients that do not recognize 
extensions to the service SHOULD ignore them.

The details of designing and implementing extensions is beyond the scope of 
this document.

NOTE: It is possible that future forward-compatible modifications to this 
specification will include new URLs, objects, arrays, properties, etc. Extension 
designers should take care to prevent future modifications from breaking or 
redefining those modifications.
